version: '3.8'

services:
  wireguard:
    image: Wireguard
    container_name: wireguard 
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=votre_IP_publique
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto  # Spécifie ici le DNS souhaité ou laisser auto 
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
